#include "stm32f103x6.h"
#include "gpio.h"

/* Enable printf() support through the UART driver.
 * This must be defined before including uart.h.
 */
#define UART_ENABLE_PRINTF

#include "uart.h"

/* Configures the MCU to run at 72 MHz.
 * The implementation is generated by STM32CubeMX or provided elsewhere.
 */
void SystemClock_Config(void);

int main(void)
{
    /*----------------------------------------------------------
     * Configure the system clock.
     *
     * The UART baud rate calculation depends on the peripheral
     * clock frequency, so configure the clock before
     * initializing the UART.
     *---------------------------------------------------------*/
    SystemClock_Config();

    /*----------------------------------------------------------
     * Configure the GPIO pins used by USART1.
     *
     * PA9  -> UART Transmit (TX)
     * PA10 -> UART Receive  (RX)
     *
     * The driver automatically configures:
     *   TX as Alternate Function Push-Pull
     *   RX as Floating Input
     *---------------------------------------------------------*/
    uart_gpio_pins_init(GPIOA, GPIO_PIN_9,
                        GPIOA, GPIO_PIN_10);

    /*----------------------------------------------------------
     * USART1 configuration
     *
     * Configure the communication parameters used by the UART.
     *---------------------------------------------------------*/
    uart_init_t uart1_cfg =
    {
        .instance     = USART1,

        /* Peripheral clock supplied to USART1.
         * USART1 is connected to APB2, which runs at 72 MHz.
         */
        .pclk_hz      = 72000000U,

        /* Communication speed */
        .baudrate     = 9600U,

        /* Standard serial configuration:
         * 8 data bits
         * No parity
         * 1 stop bit
         */
        .word_length  = UART_WORDLEN_8,
        .parity       = UART_PARITY_NONE,
        .stop_bits    = UART_STOPBITS_1,

        /* Hardware flow control is not used. */
        .flow_control = UART_FLOWCTRL_NONE
    };

    /* Initialize USART1 using the configuration above. */
    uart_init(&uart1_cfg);

    /* Send a welcome message to the serial terminal. */
    uart_write_string(USART1,
                      "STM32 ready - type a message and press Enter\r\n");

    /*----------------------------------------------------------
     * Enable the driver's built-in interrupt-driven receive
     * buffer.
     *
     * Incoming characters are stored automatically by the ISR,
     * allowing the main loop to read complete lines later.
     *---------------------------------------------------------*/
    uart_rx_buffer_enable(USART1);

    while (1)
    {
        /* Buffer used to store one received line. */
        char line[64];

        /*------------------------------------------------------
         * uart_read_line() is non-blocking.
         *
         * It returns:
         *   1 -> A complete line has been received.
         *   0 -> No complete line available yet.
         *-----------------------------------------------------*/
        if (uart_read_line(USART1, line, sizeof(line)))
        {
            /* Echo the received message back to the terminal. */
            uart_printf(USART1,
                        "You said: %s\r\n",
                        line);
        }
    }
}
